# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 16:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apks', '0002_apk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apk',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 29, 16, 18, 15, 69864), editable=False),
        ),
        migrations.AlterField(
            model_name='apk',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
