# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apks', '0003_auto_20170529_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='apk',
            name='apk',
            field=models.FileField(default='', upload_to='apk_uploads'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apk',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='apk',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
